name: Deploy Python Function App to Azure (OIDC)

on:
  push: { branches: [ "main" ] }
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps to package folder
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .python_packages/lib/site-packages
      - name: Deploy with Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: .
