name: Dropbox — Smoke

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Health
        run: |
          set -euo pipefail
          curl -fsS "${{ secrets.DBX_BASE_URL }}/api/dbx_health?code=${{ secrets.DBX_HOST_KEY }}"
