
name: Deploy to Azure (OIDC)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies to package folder
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .python_packages/lib/site-packages

      - name: Create deployment package
        run: |
          zip -r package.zip host.json requirements.txt .funcignore lib functions .python_packages db README.md

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Zip Deploy to Function App
        run: |
          az functionapp deployment source config-zip             --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}"             --name "${{ secrets.AZURE_FUNCTIONAPP_NAME }}"             --src package.zip
