name: Deploy (OIDC)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ENV_APP_NAME: altus-dropbox-integration   # ← correct Function App name
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # NEW: build the Python deps into .python_packages/
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies (vendor for Azure Functions)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .python_packages/lib/site-packages

      - name: Package function app
        run: |
          zip -r functionapp.zip . -x "*.git*" -x ".github/*" -x "node_modules/*"

      - name: Deploy via Functions Action
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.ENV_APP_NAME }}
          package: functionapp.zip
          slot-name: production
