name: Deploy (OIDC)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ENV_APP_NAME: altus-dropbox-integration   # <-- set per repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Package function app
        run: |
          rm -f functionapp.zip
          zip -r functionapp.zip . -x "*.git*" -x "node_modules/*" -x ".github/*"

      - name: Deploy via Functions Action
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.ENV_APP_NAME }}
          package: functionapp.zip
          slot-name: production
