name: Deploy to Azure (Publish Profile)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies into package folder
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .python_packages/lib/site-packages

      - name: Create deployment package
        run: |
          zip -r package.zip host.json requirements.txt .funcignore lib functions .python_packages db README.md

      # Deploy directly to Kudu with the publish profile (works for Function Apps on Linux Consumption)
      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: package.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
