name: Deploy Functions App
on:
  push:
    branches: [ main ]
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Optional local build step; not required if using remote build below
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Functions (Publish Profile)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: '.'
          # Make Kudu build the Python deps on the server:
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          respect-funcignore: true
