name: DealRoom — Deploy (OIDC)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'
      - 'host.json'
      - 'requirements.txt'
      - '.github/workflows/dr_deploy.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip package
        run: zip -r functionapp.zip . -x ".git/*" "*.pyc" "__pycache__/*" ".github/*"
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Find the resource group
        id: rg
        run: echo "val=$(az functionapp show -n altus-dealroom-api-func --query resourceGroup -o tsv)" >> "$GITHUB_OUTPUT"
      - name: Deploy zip to Function App
        run: az functionapp deployment source config-zip -g "$RG" -n altus-dealroom-api-func --src functionapp.zip
        env:
          RG: ${{ steps.rg.outputs.val }}
