name: Run Smoke Tests (Diag)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  BASE: ${{ secrets.FUNC_BASE_URL }}          # e.g. https://<app>.azurewebsites.net
  CODE: ${{ secrets.FUNC_CODE_DEFAULT }}      # default function key (string only)
  RG:   ${{ secrets.AZURE_RESOURCE_GROUP }}   # resource group name

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Detect app and build URLs (with safe fallbacks)
        id: urls
        shell: bash
        env:
          BASE: ${{ env.BASE }}
          CODE: ${{ env.CODE }}
          RG:   ${{ env.RG }}
        run: |
          set -euo pipefail
          BASE="${BASE:?FUNC_BASE_URL secret is missing}"
          CODE="${CODE:?FUNC_CODE_DEFAULT secret is missing}"
          RG="${RG:?AZURE_RESOURCE_GROUP secret is missing}"

          HOST=$(echo "$BASE" | sed -E 's#https?://([^/]+).*#\1#')
          echo "Host: $HOST"
          echo "RG:   $RG"

          # Default URLs (fallbacks)
          defurl() { echo "$BASE/api/$1?code=$CODE"; }
          DBX_HEALTH_URL=$(defurl dbx_health)
          TRANSFER_URL=$(defurl transfer_property_owner)
          UPLOAD_URL=$(defurl dropbox_upload)
          WEBHOOK_URL=$(defurl webhook_ingestor)
          WRITEBACK_URL=$(defurl doorloop_writeback)

          # Try to discover the function app & real invokeUrlTemplate
          APPS=$(az functionapp list -g "$RG" --query "[].{name:name,host:defaultHostName}" -o tsv || true)
          APP=$(echo "$APPS" | awk -v h="$HOST" '$2==h{print $1; exit}')
          [ -z "${APP:-}" ] && APP=$(echo "$APPS" | awk -v h="$HOST" 'index($2,h){print $1; exit}')

          if [ -n "${APP:-}" ]; then
            echo "Function App: $APP"
            az functionapp function list -g "$RG" -n "$APP" -o json > funcs.json
            echo "Functions deployed:"
            jq -r '.[] | [.name, .invokeUrlTemplate] | @tsv' funcs.json || true

            mk() {
              local name="$1"
              local u
              u=$(jq -r --arg N "$name" '.[] | select(.name==$N) | .invokeUrlTemplate // empty' funcs.json)
              if [ -n "$u" ] && [ "$u" != "null" ]; then
                [[ "$u" == *code=* ]] && echo "$u" || echo "$u?code=$CODE"
              fi
            }

            DBX_HEALTH_URL="${DBX_HEALTH_URL:-$(defurl dbx_health)}"
            t=$(mk transfer_property_owner); [ -n "${t:-}" ] && TRANSFER_URL="$t"
            u=$(mk dropbox_upload);          [ -n "${u:-}" ] && UPLOAD_URL="$u"
            w=$(mk webhook_ingestor);        [ -n "${w:-}" ] && WEBHOOK_URL="$w"
            d=$(mk doorloop_writeback);      [ -n "${d:-}" ] && WRITEBACK_URL="$d"
          else
            echo "Could not resolve app from RG; using fallback URLs."
          fi

          {
            echo "dbx_health_url=$DBX_HEALTH_URL"
            echo "transfer_property_owner_url=$TRANSFER_URL"
            echo "dropbox_upload_url=$UPLOAD_URL"
            echo "webhook_ingestor_url=$WEBHOOK_URL"
            echo "doorloop_writeback_url=$WRITEBACK_URL"
          } >> "$GITHUB_OUTPUT"

      - name: Show URLs we’ll call
        run: |
          echo "dbx_health:              ${{ steps.urls.outputs.dbx_health_url }}"
          echo "transfer_property_owner: ${{ steps.urls.outputs.transfer_property_owner_url }}"
          echo "dropbox_upload:          ${{ steps.urls.outputs.dropbox_upload_url }}"
          echo "webhook_ingestor:        ${{ steps.urls.outputs.webhook_ingestor_url }}"
          echo "doorloop_writeback:      ${{ steps.urls.outputs.doorloop_writeback_url }}"

      - name: Health check
        shell: bash
        run: |
          url="${{ steps.urls.outputs.dbx_health_url }}"
          echo "GET $url"
          curl -sS "$url" | jq -r .

      - name: Dry-run ownership transfer
        shell: bash
        run: |
          url="${{ steps.urls.outputs.transfer_property_owner_url }}"
          echo "POST $url"
          cat > body.json <<'JSON'
          {
            "from_owner": {"id": 101, "name": "Sunset Capital Partners"},
            "to_owner":   {"id": 202, "name": "Northstar Holdings"},
            "property":   {"id": 201, "name": "Sunset Villas"},
            "effective_date": "2025-08-15",
            "dry_run": true
          }
          JSON
          curl -sS -H "Content-Type: application/json" -d @body.json "$url" | jq -r .

      - name: Upload a tiny smoke file
        shell: bash
        run: |
          url="${{ steps.urls.outputs.dropbox_upload_url }}"
          printf "smoke %s\n" "$(date -u +%s)" > msg.txt
          b64=$(base64 -w0 msg.txt 2>/dev/null || base64 msg.txt)
          cat > body.json <<JSON
          {
            "entity_type": "LeaseSigned",
            "meta": {
              "owner_id": 101,
              "owner_name": "Sunset Capital Partners",
              "property_id": 201,
              "property_name": "Sunset Villas",
              "unit_id": 5,
              "unit_name": "unit-5b-5",
              "lease_id": 6001,
              "tenant_slug": "jane-smith"
            },
            "original_filename": "smoke.txt",
            "file_base64": "$b64"
          }
          JSON
          echo "POST $url"
          curl -sS -H "Content-Type: application/json" -d @body.json "$url" | jq -r .
